import type { Metadata } from "next";
import Image from "next/image";
import { Button } from "@/components/ui/button";
import { Outfit } from "next/font/google";
import "./globals.css";
import { Bookmark, Compass, Search } from "lucide-react";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className='w-screen h-screen bg-background'>
        {children}
        <div className="fixed bottom-0 w-screen h-fit flex flex-row bg-background-3">
          <Button className="bg-background-3 text-white w-full text-xs"><Compass /></Button>
          <Button className="bg-background-3 text-white w-full text-xs"><Bookmark /></Button>
          <Button className="bg-background-3 text-white w-full text-xs"><Search /></Button>
          <Button className="bg-background-3 text-white w-full text-xs">
            <img src="https://avatars.githubusercontent.com/u/124599?v=4" width={30} height={30} className="rounded-full" alt="avatar" />
          </Button>
        </div>
      </body>
    </html>
  );
}
